<?php
/**
 * @file
 * ig_event_feature.features.inc
 */

/**
 * Implements hook_node_info().
 */
function ig_event_feature_node_info() {
  $items = array(
    'event' => array(
      'name' => t('Event'),
      'base' => 'node_content',
      'description' => t('An instagram event container'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
