<?php
/**
 * @file
 * Code for the Instagram Base feature.
 */

include_once 'ig_base_feature.features.inc';

/**
 * Implements hook_element_info_alter().
 */
function ig_base_feature_element_info_alter(&$types) {
  if (isset($types['password_confirm']['#process']) && (($position = array_search('user_form_process_password_confirm', $types['password_confirm']['#process'])) !== FALSE)) {
    unset($types['password_confirm']['#process'][$position]);
  }
}